name: footprint-tools
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python>=3.6
- pip
- tqdm
- cython
- numpy
- scipy
- pandas
- pysam
- statsmodels
- simplejson
- tqdm
- click
- click-option-group
- matplotlib

- pip:
  - pwlf
  - genome-tools==1.0.4
  - yaspin
  - .
