name: footprint-tools
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python>=3.6
- pip
- tqdm
- cython
- numpy
- scipy
- pandas
- pysam
- statsmodels
- simplejson
- tqdm
- click
- click-option-group
- matplotlib
- bumpversion
- sphinx
- nbsphinx
- ipykernel
- sphinx-panels
- pydata-sphinx-theme
- numpydoc
- pandoc

- pip:
  - git+https://github.com/jvierstra/sphinx-click.git
  - genome-tools==1.0.4
  - pwlf
  - yaspin