#!/usr/env python

from __future__ import absolute_import
from __future__ import print_function
import sys

import numpy as np
import scipy.stats

from footprint_tools.modeling import dispersion

dm = dispersion.read_dispersion_model(sys.argv[1])
print(sys.argv[1], dm.mu_params)
